### ISSUE TITLE
Приложение не подключается к контейнерной БД

### ISSUE THREAD

**Issue by artemglinov** [artemglinov/webmvc#1]
@coursar Вставил значение параметра CATALINA_OPTS из вашего письма - всё то же самое. 
Stacktrace (после выполнения тестового запроса на регистрацию заказа):

<body><h1>HTTP Status 500 – Internal Server Error</h1>
<hr class="line"/>
<p><b>Type</b> Exception Report</p>
<p><b>Message</b> Request processing failed; nested exception is
    org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is
    java.sql.SQLException: Cannot create PoolableConnectionFactory (ВАЖНО: база данных &quot;db&quot; не существует
    (pgjdbc: autodetected server-encoding to be windows-1251, if the message is not readable, please check database logs
    and&#47;or host, port, dbname, user, password, pg_hba.conf))</p>
<p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p>
<p><b>Exception</b></p>
<pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (ВАЖНО: база данных &quot;db&quot; не существует (pgjdbc: autodetected server-encoding to be windows-1251, if the message is not readable, please check database logs and&#47;or host, port, dbname, user, password, pg_hba.conf))
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre>
<p><b>Root Cause</b></p>
<pre>org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (ВАЖНО: база данных &quot;db&quot; не существует (pgjdbc: autodetected server-encoding to be windows-1251, if the message is not readable, please check database logs and&#47;or host, port, dbname, user, password, pg_hba.conf))
	org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
	org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:646)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:757)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:815)
	org.example.repository.UserRepository.isUserPresent(UserRepository.java:23)
	org.example.auth.AuthManager.authenticate(AuthManager.java:16)
	org.example.service.OrderService.authenticate(OrderService.java:54)
	org.example.service.OrderService.register(OrderService.java:26)
	org.example.controller.OrderController.register(OrderController.java:35)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	java.base&#47;jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base&#47;java.lang.reflect.Method.invoke(Method.java:567)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre>
<p><b>Root Cause</b></p>
<pre>java.sql.SQLException: Cannot create PoolableConnectionFactory (ВАЖНО: база данных &quot;db&quot; не существует (pgjdbc: autodetected server-encoding to be windows-1251, if the message is not readable, please check database logs and&#47;or host, port, dbname, user, password, pg_hba.conf))
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:655)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:533)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:733)
	org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:646)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:757)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:815)
	org.example.repository.UserRepository.isUserPresent(UserRepository.java:23)
	org.example.auth.AuthManager.authenticate(AuthManager.java:16)
	org.example.service.OrderService.authenticate(OrderService.java:54)
	org.example.service.OrderService.register(OrderService.java:26)
	org.example.controller.OrderController.register(OrderController.java:35)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	java.base&#47;jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base&#47;java.lang.reflect.Method.invoke(Method.java:567)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre>
<p><b>Root Cause</b></p>
<pre>org.postgresql.util.PSQLException: ВАЖНО: база данных &quot;db&quot; не существует (pgjdbc: autodetected server-encoding to be windows-1251, if the message is not readable, please check database logs and&#47;or host, port, dbname, user, password, pg_hba.conf)
	org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2664)
	org.postgresql.core.v3.QueryExecutorImpl.&lt;init&gt;(QueryExecutorImpl.java:147)
	org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:273)
	org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	org.postgresql.jdbc.PgConnection.&lt;init&gt;(PgConnection.java:223)
	org.postgresql.Driver.makeConnection(Driver.java:465)
	org.postgresql.Driver.connect(Driver.java:264)
	org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
	org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:369)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:102)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:651)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:533)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:733)
	org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:646)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:757)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:815)
	org.example.repository.UserRepository.isUserPresent(UserRepository.java:23)
	org.example.auth.AuthManager.authenticate(AuthManager.java:16)
	org.example.service.OrderService.authenticate(OrderService.java:54)
	org.example.service.OrderService.register(OrderService.java:26)
	org.example.controller.OrderController.register(OrderController.java:35)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	java.base&#47;jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base&#47;java.lang.reflect.Method.invoke(Method.java:567)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre>
<p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p>
<hr class="line"/>
<h3>Apache Tomcat/9.0.50</h3></body>
</html>

**Comment by artemglinov** [comment]
В терминале во время выполнения docker-compose up появляется следующее:

Creating network "webmvc-master_default" with the default driver
Creating webmvc-master_db_1 ... done
Attaching to webmvc-master_db_1
db_1  | The files belonging to this database system will be owned by user "postgres".
db_1  | This user must also own the server process.
db_1  |
db_1  | The database cluster will be initialized with locale "en_US.utf8".
db_1  | The default database encoding has accordingly been set to "UTF8".
db_1  | The default text search configuration will be set to "english".
db_1  |
db_1  | Data page checksums are disabled.
db_1  |
db_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1  | creating subdirectories ... ok
db_1  | selecting dynamic shared memory implementation ... posix
db_1  | selecting default max_connections ... 100
db_1  | selecting default shared_buffers ... 128MB
db_1  | selecting default time zone ... UTC
db_1  | creating configuration files ... ok
db_1  | running bootstrap script ... ok
db_1  | performing post-bootstrap initialization ... sh: locale: not found
db_1  | 2021-07-19 08:16:45.334 UTC [31] WARNING:  no usable system locales were found
db_1  | ok
db_1  | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
db_1  | You can change this by editing pg_hba.conf or using the option -A, or
db_1  | --auth-local and --auth-host, the next time you run initdb.
db_1  | ok
db_1  |
db_1  |
db_1  | Success. You can now start the database server using:
db_1  |
db_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1  |
db_1  | waiting for server to start....2021-07-19 08:16:45.876 UTC [36] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-musl, compile
d by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
db_1  | 2021-07-19 08:16:45.882 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1  | 2021-07-19 08:16:45.899 UTC [37] LOG:  database system was shut down at 2021-07-19 08:16:45 UTC
db_1  | 2021-07-19 08:16:45.906 UTC [36] LOG:  database system is ready to accept connections
db_1  |  done
db_1  | server started
db_1  | CREATE DATABASE
db_1  |
db_1  |
db_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00_schema.sql
db_1  | CREATE TABLE
db_1  | CREATE TABLE
db_1  |
db_1  |
db_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01_data.sql
db_1  | INSERT 0 1
db_1  | INSERT 0 1
db_1  |
db_1  |
db_1  | waiting for server to shut down...2021-07-19 08:16:46.212 UTC [36] LOG:  received fast shutdown request
db_1  | .2021-07-19 08:16:46.217 UTC [36] LOG:  aborting any active transactions
db_1  | 2021-07-19 08:16:46.218 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
db_1  | 2021-07-19 08:16:46.218 UTC [38] LOG:  shutting down
db_1  | 2021-07-19 08:16:46.269 UTC [36] LOG:  database system is shut down
db_1  |  done
db_1  | server stopped
db_1  |
db_1  | PostgreSQL init process complete; ready for start up.
db_1  |
db_1  | 2021-07-19 08:16:46.334 UTC [1] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210
424) 10.3.1 20210424, 64-bit
db_1  | 2021-07-19 08:16:46.334 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1  | 2021-07-19 08:16:46.334 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1  | 2021-07-19 08:16:46.346 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1  | 2021-07-19 08:16:46.358 UTC [54] LOG:  database system was shut down at 2021-07-19 08:16:46 UTC
db_1  | 2021-07-19 08:16:46.366 UTC [1] LOG:  database system is ready to accept connections

**Comment by coursar** [comment]
Выберите завтра время - подключусь к вам удалённо, посмотрим.

**Comment by artemglinov** [comment]
Всё поправил - убил пару процессов, и заработало. Теперь осталось с GitHub Container Registry разобраться.

**Comment by artemglinov** [comment]
Я думаю, можно проверять.
